// Generated by https://quicktype.io

export interface Characters {
    info:    Info;
    results: Character[];
}

export interface Info {
    count: number;
    pages: number;
    next:  string;
    prev:  null;
}

export interface Character {
    id:       number;
    name:     string;
    status:   Status;
    species:  Species;
    image:    string;
}

enum Species {
    Alien = "Alien",
    Human = "Human",
}

enum Status {
    Alive = "Alive",
    Dead = "Dead",
    Unknown = "unknown",
}

export interface Card {
    id:               number;
    name:             string;
    status:           Status;
    species:          Species;
    image:            string;
    [ key: string ]:  any;
    //active?:  "hidden" | "checking" | "visible"  //CardStatus | undefined;
}

/* enum CardStatus {
    hidden = "hidden",
    checking = "checking",
    visible = "visible",
} */